export const REQUEST_SYMBOL = "REQUEST_SYMBOL"
export const SYMBOL_SUCCESS = "SYMBOL_SUCCESS"
export const SYMBOL_FAILURE = "SYMBOL_FAILURE"

export const UPDATE_TICKER_DATA = "UPDATE_TICKER_DATA"
export const UPDATE_CANDLE_DATA = "UPDATE_CANDLE_DATA"